### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TokyoghoulEs** [Evanito/Pifiltrator#1]
Traceback (most recent call last):
  File "infiltrate.py", line 178, in <module>
    print "\n This is what we know:\n%s" %(populate_known()) 
  File "infiltrate.py", line 113, in populate_known
    with open('%s/cracked.csv' %(path), mode='r') as knowns:
IOError: [Errno 2] No such file or directory: '/root/cracked.csv'

**Comment by Evanito** [comment]
This file is created for the first time when successfully cracking a WiFi AP with Wifite, I will have it created by the script to solve this.

**Comment by Evanito** [comment]
This issue has been resolved in the most recent version.
