### ISSUE TITLE
test_mode = True

### ISSUE THREAD

**Issue by TokyoghoulEs** [Evanito/Pifiltrator#3]
Traceback (most recent call last):
  File "infiltrate.py", line 191, in <module>
    sniff(iface=interface, prn = PacketHandler, timeout=10)
  File "/usr/lib/python2.7/site-packages/scapy/sendrecv.py", line 577, in sniff
    p = s.recv(MTU)
  File "/usr/lib/python2.7/site-packages/scapy/arch/linux.py", line 493, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
socket.error: [Errno 100] Network is down

**Comment by TokyoghoulEs** [comment]
socket.error: [Errno 100] Network is down

#!/bin/bash

# Script: reset_iface v2

# Por geminis_demon para Wifislax - SeguridadWireless.Net

Error() {

```
    echo " - ERROR: $1"
    exit 1
```

}

if [ -z "$1" -o "$1" = "-h" ]; then

```
    echo
    echo "Este script desmonta y vuelve a montar el driver de una interfaz de red"
    echo 
    echo "EJEMPLO:"
    echo " $0 wlan0"
    echo
    echo "OPCIONES:"
    echo " -h  Muestra esta ayuda."
    echo 

    if [ -z "$1" ]; then
            exit 1
    else
            exit 0
    fi
```

fi

[ $(id -u) != 0 ] && Error "Este script debe ejecutarse con permisos de ROOT"
[ ! -d "/sys/class/net/$1/device/driver" ] && Error "No existe la interfaz $1"
ID="$(basename "$(ls -l "/sys/class/net/$1/device")")"
OLD_DIR="$(pwd)"
cd "/sys/class/net/$1/device/driver/"
echo -n "$ID" >unbind||Error "Ocurrió un problema al desmontar la interfaz $1"
echo -n "$ID" >bind||Error "Ocurrió un problema al montar la interfaz $1"
echo " - La interfaz $1 ha sido reiniciada"
cd "$OLD_DIR"

**Comment by Evanito** [comment]
I am unable to recreate this bug, it seems to be the result of an issue with wireless interface drivers on your end.

**Comment by Evanito** [comment]
Actually, try this before running it.
`service network-manager stop`
or
`airmon-ng check kill`
