### ISSUE TITLE
Wifite no instalado / Wifite not found

### ISSUE THREAD

**Issue by TokyoghoulEs** [Evanito/Pifiltrator#4]
Si wifite no esta instalado entra en un bucle de reinicio.

If wifite is not installed enter a reboot loop.

**Comment by Evanito** [comment]
This program requires the program **Wifite** on _LINUX_ in order to run, in the future there will be a check for this, wait till next merge. For now, install wifite using:
`apt-get install wifite`

**Comment by Evanito** [comment]
Solved in #5
