### ISSUE TITLE
Internet Found! Internet eth0 impossible to continue

### ISSUE THREAD

**Issue by TokyoghoulEs** [Evanito/Pifiltrator#7]
Pifiltrator by Evanito

Started, checking for internet...
Scanning for wireless devices since none was stated.
Using wireless interface: wlan0
Internet Found!
root@kali:~#

**Comment by Evanito** [comment]
- Where do you get the exception `Internet eth0 impossible to continue`? 
- Are you using the email sending feature?
- What arguments are you running with (you may remove/edit sensitive data but keep the @domain.com so I know which email provider you are using.)
- The body of your message shows normal operation, use --testmode to scan anyway even when Internet is found.
