### ISSUE TITLE
What sources.list do I need?

### ISSUE THREAD

**Issue by TokyoghoulEs** [Evanito/Pifiltrator#8]
Linux kali 4.1.19 #1 PREEMPT Tue Mar 15 18:12:17 CDT 2016 armv6l GNU/Linux

deb http://http.kali.org/kali kali-rolling main non-free contrib
deb-src http://http.kali.org/kali kali-rolling main non-free contrib
# realtek

deb http://ftp.us.debian.org/debian/ squeeze main non-free
deb http://security.debian.org/ squeeze/updates main non-free
deb http://security.debian.org/ squeeze/updates main non-free
deb http://security.debian.org/ squeeze/updates main non-free

¿Es necesario algún otro repositorio para instalar las herramientas que no tenga la distro?

Are there any other repository is required to install the tools not have the distro ?

**Comment by Evanito** [comment]
All the Libraries used are already found in Python 2.7 in kali linux, and the only other tools are Wifite and its dependencies, so there are no other repositories or sources needed.

Are you having issues running it?
